### ISSUE TITLE
How to handle 2 games at once

### ISSUE THREAD

**Issue by polevaultweb** [gilbitron/world-cup-2018#20]
![image](https://user-images.githubusercontent.com/1770201/41837576-db375cf6-7855-11e8-80b9-7687b3561cb7.png)

The end of the group stages have 2 games at once, we need to decide how to display that as the tray only can have 1 match

**Comment by gilbitron** [comment]
I think displaying both games in the title is fine:

```
KSA 0 - 0 EGY (HT) / URU 0 - 0 RUS (HT)
```

The events sections for each game will need a separator between them.

**Comment by polevaultweb** [comment]
I'll fix up in a bit
